### ISSUE TITLE
Error while starting pymeterreader-wizard

### ISSUE THREAD

**Issue by mattt3** [Schwaneberg/pymeterreader#5]
Hello,

getting this error while starting the wizard.

```
$ sudo pymeterreader-wizard
Detecting meters...
ERROR:pymeterreader.device_lib.serial_reader:Uncaught Exception while tyring to detect SML Meter! Please report this to the developers.
Traceback (most recent call last):
  File "/usr/local/bin/pymeterreader-wizard", line 10, in <module>
    sys.exit(Wizard())
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/wizard/ncui.py", line 32, in __init__
    self.meters = detect()
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/wizard/detector.py", line 14, in detect
    devices.extend(SmlReader.detect())
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/device_lib/meter_sml.py", line 82, in detect
    return SmlReader("loop://")._detect_serial_devices(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/device_lib/serial_reader.py", line 90, in _detect_serial_devices
    device = serial_reader_implementation._discover()
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/device_lib/meter_sml.py", line 88, in _discover
    sample = self.fetch()
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/device_lib/base.py", line 83, in fetch
    sample = self._fetch_untracked()
  File "/usr/local/lib/python3.7/dist-packages/pymeterreader/device_lib/meter_sml.py", line 50, in _fetch_untracked
    serial_port.read_until(expected=self.__START_SEQ)
TypeError: read_until() got an unexpected keyword argument 'expected'
```

Raspberry Pi 3 Model B Rev 1.2
Raspbian GNU/Linux 10 (buster)
Linux vzlogger 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

**Comment by Schwaneberg** [comment]
Hello!
This exception is caused by an incompatible API call of SerialBase.read_until from pyserial.
Please try upgrading pyserial to version 3.5.

**Comment by mattt3** [comment]
I can confirm that running `sudo python3 -m pip install --upgrade pyserial` solved this issue. Version 3.4 was installed system-wide. Seems to be related to different Python versions which are installed.
