### ISSUE TITLE
Erorr while starting pymeterreader-wizard

### ISSUE THREAD

**Issue by gruessung** [Schwaneberg/pymeterreader#6]
``` pi@powerlogger:~ $ sudo pymeterreader-wizard
Traceback (most recent call last):
  File "/usr/local/bin/pymeterreader-wizard", line 5, in <module>
    from pymeterreader.wizard.ncui import Wizard
  File "/usr/local/lib/python3.9/dist-packages/pymeterreader/wizard/ncui.py", line 12, in <module>
    from cursesmenu import CursesMenu
  File "/usr/local/lib/python3.9/dist-packages/cursesmenu/__init__.py", line 1, in <module>
    from . import items
  File "/usr/local/lib/python3.9/dist-packages/cursesmenu/items/__init__.py", line 2, in <module>
    from .exit_item import ExitItem
  File "/usr/local/lib/python3.9/dist-packages/cursesmenu/items/exit_item.py", line 5, in <module>
    from cursesmenu.curses_menu import CursesMenu
  File "/usr/local/lib/python3.9/dist-packages/cursesmenu/curses_menu.py", line 12, in <module>
    from deprecated import deprecated
ModuleNotFoundError: No module named 'deprecated'
```

**Comment by Schwaneberg** [comment]
This error was caused by curses-menu 0.6.x. I changed it to require 0.5.0 explicitly. Please try upgrading to pymeterreader 0.2.2
